import type {
  AccessCode,
  InventoryItem,
  Location,
  Material,
  Project,
  PurchaseOrder,
  Settings,
  StoreState,
  Tool,
  Transaction,
} from "./types";
import { decodeToolsFromPersist } from "./tools-state";

function isoDaysAgo(days: number, hours = 10) {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hours, 15, 0, 0);
  return d.toISOString();
}

export const defaultSettings: Settings = {
  company_name: "Summit Electric",
  logo_url: "/logo.png",
  primary_color: "#12203a",
  accent_color: "#f97316",
  buildr_linked: true,
  buildr_company_id: "co_summit_demo",
};

const locations: Location[] = [
  {
    id: "loc-wh-main",
    name: "Main Warehouse",
    type: "warehouse",
    description: "Central stock room on 12th Street",
  },
  {
    id: "loc-shop",
    name: "Shop",
    type: "warehouse",
    description: "Prefabrication bench and overflow racks",
  },
  {
    id: "loc-truck-12",
    name: "Truck 12",
    type: "vehicle",
    assigned_to: "Mike Alvarez",
    description: "Service van — north route",
  },
  {
    id: "loc-truck-7",
    name: "Truck 7",
    type: "vehicle",
    assigned_to: "Dana Cho",
    description: "Service van — commercial crew",
  },
];

const materials: Material[] = [
  {
    id: "mat-emt-34",
    name: '3/4" EMT Conduit',
    description: "Electrical metallic tubing, 10 ft sticks",
    category: "Conduit",
    sub_category: "EMT",
    manufacturer: "Allied Tube",
    supplier: "Crescent Electric",
    unit: "ft",
    unit_cost: 1.12,
    barcode: "012345678901",
    reorder_point: 400,
    min_stock_level: 200,
    aliases: ["emt", "3/4 emt", "conduit"],
  },
  {
    id: "mat-pvc-12",
    name: '1/2" PVC Conduit',
    description: "Schedule 40 PVC, 10 ft sticks",
    category: "Conduit",
    sub_category: "PVC",
    manufacturer: "Cantex",
    supplier: "Crescent Electric",
    unit: "ft",
    unit_cost: 0.64,
    barcode: "012345678918",
    reorder_point: 250,
    min_stock_level: 100,
    aliases: ["pvc", "plastic conduit"],
  },
  {
    id: "mat-thhn-12",
    name: "#12 THHN Black",
    description: "500 ft spool, stranded",
    category: "Wire",
    sub_category: "THHN",
    manufacturer: "Southwire",
    supplier: "Crescent Electric",
    unit: "ft",
    unit_cost: 0.28,
    barcode: "045678912345",
    reorder_point: 1500,
    min_stock_level: 500,
    aliases: ["thhn", "number 12", "#12"],
  },
  {
    id: "mat-romex",
    name: "12/2 NM-B Romex",
    description: "250 ft coil, yellow jacket",
    category: "Wire",
    sub_category: "NM-B",
    manufacturer: "Southwire",
    supplier: "Crescent Electric",
    unit: "ft",
    unit_cost: 0.72,
    barcode: "045678912352",
    reorder_point: 800,
    min_stock_level: 250,
    aliases: ["romex", "nm-b", "12/2"],
  },
  {
    id: "mat-brk-20",
    name: "20A Single Pole Breaker",
    description: "QO / compatible 20 amp SP",
    category: "Electrical",
    sub_category: "Breakers",
    manufacturer: "Square D",
    supplier: "Crescent Electric",
    unit: "each",
    unit_cost: 8.45,
    barcode: "078912345678",
    reorder_point: 24,
    min_stock_level: 8,
    aliases: ["breaker", "20a breaker"],
  },
  {
    id: "mat-box-4",
    name: '4" Square Box',
    description: "1-1/2 in deep steel box",
    category: "Electrical",
    sub_category: "Boxes",
    manufacturer: "Raco",
    supplier: "Crescent Electric",
    unit: "each",
    unit_cost: 1.85,
    barcode: "078912345685",
    reorder_point: 80,
    min_stock_level: 30,
    aliases: ["square box", "4 square"],
  },
  {
    id: "mat-duplex",
    name: "Duplex Receptacle 20A",
    description: "Commercial spec grade, ivory",
    category: "Electrical",
    sub_category: "Devices",
    manufacturer: "Leviton",
    supplier: "Crescent Electric",
    unit: "each",
    unit_cost: 2.4,
    barcode: "081234567890",
    reorder_point: 50,
    min_stock_level: 20,
    aliases: ["receptacle", "outlet", "duplex"],
  },
  {
    id: "mat-troffer",
    name: "LED 2x4 Troffer",
    description: "4000K, 40W, 0-10V dimming",
    category: "Lighting",
    sub_category: "Fixtures",
    manufacturer: "Lithonia",
    supplier: "Crescent Electric",
    unit: "each",
    unit_cost: 68,
    barcode: "081234567907",
    reorder_point: 8,
    min_stock_level: 2,
    aliases: ["troffer", "2x4", "fixture"],
  },
  {
    id: "mat-screws",
    name: "Self-Tapping Screws",
    description: "#10 x 3/4 in, 100-count box",
    category: "Hardware",
    sub_category: "Fasteners",
    manufacturer: "Grabber",
    supplier: "Fastenal",
    unit: "box",
    unit_cost: 6.1,
    barcode: "099887766554",
    reorder_point: 12,
    min_stock_level: 4,
    aliases: ["screws", "tapping screws"],
  },
  {
    id: "mat-nuts",
    name: "Wire Nuts Assortment",
    description: "Red / yellow / orange, 500-count",
    category: "Hardware",
    sub_category: "Connectors",
    manufacturer: "Ideal",
    supplier: "Crescent Electric",
    unit: "box",
    unit_cost: 18.5,
    barcode: "099887766561",
    reorder_point: 6,
    min_stock_level: 2,
    aliases: ["wire nuts", "connectors"],
  },
];

const inventory: InventoryItem[] = [
  { id: "inv-1", material_id: "mat-emt-34", location_id: "loc-wh-main", quantity: 820 },
  { id: "inv-2", material_id: "mat-emt-34", location_id: "loc-truck-12", quantity: 60 },
  { id: "inv-3", material_id: "mat-pvc-12", location_id: "loc-wh-main", quantity: 140 },
  { id: "inv-4", material_id: "mat-thhn-12", location_id: "loc-wh-main", quantity: 2400 },
  { id: "inv-5", material_id: "mat-thhn-12", location_id: "loc-truck-7", quantity: 180 },
  { id: "inv-6", material_id: "mat-romex", location_id: "loc-wh-main", quantity: 310 },
  { id: "inv-7", material_id: "mat-brk-20", location_id: "loc-wh-main", quantity: 42 },
  { id: "inv-8", material_id: "mat-brk-20", location_id: "loc-truck-12", quantity: 6 },
  { id: "inv-9", material_id: "mat-box-4", location_id: "loc-wh-main", quantity: 160 },
  { id: "inv-10", material_id: "mat-box-4", location_id: "loc-shop", quantity: 48 },
  { id: "inv-11", material_id: "mat-duplex", location_id: "loc-wh-main", quantity: 18 },
  { id: "inv-12", material_id: "mat-troffer", location_id: "loc-wh-main", quantity: 14 },
  { id: "inv-13", material_id: "mat-screws", location_id: "loc-wh-main", quantity: 22 },
  { id: "inv-14", material_id: "mat-screws", location_id: "loc-truck-7", quantity: 3 },
  { id: "inv-15", material_id: "mat-nuts", location_id: "loc-wh-main", quantity: 9 },
  { id: "inv-16", material_id: "mat-nuts", location_id: "loc-truck-12", quantity: 1 },
];

const transactions: Transaction[] = [
  {
    id: "tx-1",
    type: "use",
    material_id: "mat-emt-34",
    quantity: 40,
    from_location_id: "loc-truck-12",
    project: "Riverside Electrical",
    created_at: isoDaysAgo(0, 8),
    created_by: "mike@summit.local",
  },
  {
    id: "tx-2",
    type: "transfer",
    material_id: "mat-brk-20",
    quantity: 8,
    from_location_id: "loc-wh-main",
    to_location_id: "loc-truck-12",
    created_at: isoDaysAgo(0, 7),
    created_by: "dana@summit.local",
  },
  {
    id: "tx-3",
    type: "add",
    material_id: "mat-thhn-12",
    quantity: 500,
    to_location_id: "loc-wh-main",
    notes: "PO-2608-014",
    created_at: isoDaysAgo(1, 14),
    created_by: "system",
  },
  {
    id: "tx-4",
    type: "use",
    material_id: "mat-duplex",
    quantity: 12,
    from_location_id: "loc-wh-main",
    project: "Oak Street Retrofit",
    created_at: isoDaysAgo(1, 11),
    created_by: "dana@summit.local",
  },
  {
    id: "tx-5",
    type: "use",
    material_id: "mat-troffer",
    quantity: 6,
    from_location_id: "loc-wh-main",
    project: "Oak Street Retrofit",
    created_at: isoDaysAgo(2, 15),
    created_by: "mike@summit.local",
  },
  {
    id: "tx-6",
    type: "adjust",
    material_id: "mat-romex",
    quantity: 310,
    to_location_id: "loc-wh-main",
    notes: "Cycle count",
    created_at: isoDaysAgo(3, 9),
    created_by: "system",
  },
  {
    id: "tx-7",
    type: "shrink",
    material_id: "mat-screws",
    quantity: 2,
    from_location_id: "loc-truck-7",
    notes: "Damaged box",
    created_at: isoDaysAgo(4, 16),
    created_by: "dana@summit.local",
  },
  {
    id: "tx-8",
    type: "transfer",
    material_id: "mat-emt-34",
    quantity: 80,
    from_location_id: "loc-wh-main",
    to_location_id: "loc-truck-12",
    created_at: isoDaysAgo(5, 8),
    created_by: "mike@summit.local",
  },
];

const purchaseOrders: PurchaseOrder[] = [
  {
    id: "po-1",
    po_number: "PO-2608-014",
    supplier: "Crescent Electric",
    expected_delivery: isoDaysAgo(-2).slice(0, 10),
    status: "partial",
    created_at: isoDaysAgo(6, 10),
    lines: [
      {
        material_id: "mat-thhn-12",
        expected_quantity: 1000,
        received_quantity: 500,
        unit_cost: 0.28,
      },
      {
        material_id: "mat-brk-20",
        expected_quantity: 48,
        received_quantity: 0,
        unit_cost: 8.45,
      },
    ],
  },
  {
    id: "po-2",
    po_number: "PO-2608-021",
    supplier: "Crescent Electric",
    expected_delivery: isoDaysAgo(-5).slice(0, 10),
    status: "ordered",
    created_at: isoDaysAgo(2, 12),
    lines: [
      {
        material_id: "mat-troffer",
        expected_quantity: 24,
        received_quantity: 0,
        unit_cost: 68,
      },
      {
        material_id: "mat-duplex",
        expected_quantity: 100,
        received_quantity: 0,
        unit_cost: 2.4,
      },
    ],
  },
  {
    id: "po-3",
    po_number: "PO-2607-088",
    supplier: "Fastenal",
    expected_delivery: isoDaysAgo(8).slice(0, 10),
    status: "received",
    created_at: isoDaysAgo(12, 9),
    lines: [
      {
        material_id: "mat-screws",
        expected_quantity: 20,
        received_quantity: 20,
        unit_cost: 6.1,
      },
    ],
  },
];

const accessCodes: AccessCode[] = [
  {
    id: "ac-1",
    code: "SUMMIT-TRIAL",
    type: "trial",
    label: "John Smith - Trial",
    expires_at: isoDaysAgo(-14),
    is_active: true,
    created_at: isoDaysAgo(3, 12),
  },
];

const projects: Project[] = [
  {
    id: "prj-riverside",
    name: "Riverside Electrical",
    project_number: "P-4412",
    status: "active",
  },
  {
    id: "prj-oak",
    name: "Oak Street Retrofit",
    project_number: "P-4398",
    status: "active",
  },
  {
    id: "prj-clinic",
    name: "West Clinic Panel Upgrade",
    project_number: "P-4401",
    status: "bidding",
  },
  {
    id: "prj-shop",
    name: "Shop Lighting Swap",
    project_number: "P-4280",
    status: "completed",
  },
];

const tools: Tool[] = [
  {
    id: "tool-meter",
    name: "Fluke 117 Multimeter",
    description: "True-RMS digital multimeter",
    category: "Meters",
    barcode: "TOOL117001",
    assigned_location_id: "loc-truck-12",
    assigned_to: "Mike Alvarez",
    status: "available",
  },
  {
    id: "tool-drill",
    name: "Milwaukee Hammer Drill",
    description: "M18 Fuel 1/2 in hammer drill",
    category: "Power tools",
    barcode: "TOOLDRL018",
    assigned_location_id: "loc-wh-main",
    status: "available",
  },
  {
    id: "tool-toner",
    name: "Ideal Circuit Tracer",
    category: "Testing",
    barcode: "TOOLTRC220",
    assigned_location_id: "loc-truck-7",
    assigned_to: "Dana Cho",
    status: "checked_out",
  },
];

export function normalizeStoreState(state: StoreState): StoreState {
  return decodeToolsFromPersist({
    ...state,
    settings: state.settings,
    locations: state.locations || [],
    materials: state.materials || [],
    inventory: state.inventory || [],
    transactions: state.transactions || [],
    purchaseOrders: state.purchaseOrders || [],
    accessCodes: state.accessCodes || [],
    projects: state.projects || [],
    tools: state.tools || [],
  });
}

export function createSeedState(): StoreState {
  return {
    settings: { ...defaultSettings },
    locations: structuredClone(locations),
    materials: structuredClone(materials),
    inventory: structuredClone(inventory),
    transactions: structuredClone(transactions),
    purchaseOrders: structuredClone(purchaseOrders),
    accessCodes: structuredClone(accessCodes),
    projects: structuredClone(projects),
    tools: structuredClone(tools),
  };
}

export function createEmptyState(companyName: string): StoreState {
  return {
    settings: {
      company_name: companyName,
      logo_url: "/logo.png",
      primary_color: "#12203a",
      accent_color: "#f97316",
      buildr_linked: false,
      buildr_company_id: "",
    },
    locations: [],
    materials: [],
    inventory: [],
    transactions: [],
    purchaseOrders: [],
    accessCodes: [],
    projects: [],
    tools: [],
  };
}
